// /src/converter-routes.js
// SEO-optimized converter pages for popular timezone searches

export const CONVERTER_ROUTES = {
  // IST (India) conversions - very high search volume
  "ist-to-london": {
    title: "IST to London Time Converter",
    shortTitle: "IST → London",
    subtitle: "Convert Indian Standard Time to London (GMT/BST)",
    fromCity: "India",
    toCity: "London",
    fromZone: "Asia/Kolkata",
    toZone: "Europe/London",
    fromGMT: "GMT+5:30",
    toGMT: "GMT+0/+1",
    timeDiff: "5.5 hours behind",
    description: "India Standard Time (IST) is 5 hours and 30 minutes ahead of Greenwich Mean Time (GMT). When it's noon in India, it's 6:30 AM in London. During British Summer Time (BST), the difference reduces to 4.5 hours.",
    dstNote: "London observes Daylight Saving Time (BST) from late March to late October, reducing the time difference to 4.5 hours.",
    useCases: [
      "Scheduling calls with UK clients or colleagues",
      "Coordinating with London-based tech companies",
      "Planning business meetings across India and UK",
      "Managing offshore development teams",
    ],
    bestTimes: "The best overlap for business calls is 1:30 PM - 6:30 PM IST (8:00 AM - 1:00 PM London). This ensures both parties are within standard working hours.",
    tips: [
      "Set calendar events in UTC to avoid DST confusion",
      "Remember UK clocks change twice a year - adjust your schedule accordingly",
      "Early morning IST (7-9 AM) catches late afternoon in London",
    ],
    relatedRoutes: ["ist-to-est", "ist-to-pst", "ist-to-gmt", "london-to-ist"],
  },

  "ist-to-est": {
    title: "IST to EST Time Converter",
    shortTitle: "IST → EST",
    subtitle: "Convert Indian Standard Time to US Eastern Time",
    fromCity: "India",
    toCity: "New York",
    fromZone: "Asia/Kolkata",
    toZone: "America/New_York",
    fromGMT: "GMT+5:30",
    toGMT: "GMT-5/-4",
    timeDiff: "10.5 hours behind",
    description: "India Standard Time (IST) is 10.5 hours ahead of Eastern Standard Time (EST). When it's noon in India, it's 1:30 AM in New York. The gap reduces to 9.5 hours during Eastern Daylight Time (EDT).",
    dstNote: "The US observes Daylight Saving Time from March to November, reducing the time difference to 9.5 hours during EDT.",
    useCases: [
      "Working with US East Coast clients",
      "Coordinating with Wall Street financial teams",
      "Managing US-India development teams",
      "Scheduling interviews with US companies",
    ],
    bestTimes: "The limited overlap window is 7:00 PM - 10:30 PM IST (8:30 AM - 12:00 PM EST). Evening calls in India align with US morning business hours.",
    tips: [
      "Morning standup calls often work at 8-9 PM IST",
      "The US has multiple time zones - confirm which one your contact is in",
      "Consider alternating meeting times to share the inconvenience",
    ],
    relatedRoutes: ["ist-to-pst", "ist-to-cst", "est-to-ist", "ist-to-london"],
  },

  "ist-to-pst": {
    title: "IST to PST Time Converter",
    shortTitle: "IST → PST",
    subtitle: "Convert Indian Standard Time to US Pacific Time",
    fromCity: "India",
    toCity: "San Francisco",
    fromZone: "Asia/Kolkata",
    toZone: "America/Los_Angeles",
    fromGMT: "GMT+5:30",
    toGMT: "GMT-8/-7",
    timeDiff: "13.5 hours behind",
    description: "India Standard Time (IST) is 13.5 hours ahead of Pacific Standard Time (PST). When it's noon in India, it's 10:30 PM the previous day in California. This is one of the most challenging timezone pairs for real-time collaboration.",
    dstNote: "During Pacific Daylight Time (PDT) from March to November, the difference reduces to 12.5 hours.",
    useCases: [
      "Working with Silicon Valley tech companies",
      "Coordinating with West Coast startups",
      "Managing India-California development teams",
      "Scheduling calls with Bay Area clients",
    ],
    bestTimes: "The best overlap is 8:00 PM - 11:00 PM IST (6:30 AM - 9:30 AM PST). Late evening in India catches early morning in California.",
    tips: [
      "Consider async communication for day-to-day updates",
      "Record important meetings for team members who can't attend live",
      "Use shared documents instead of real-time meetings when possible",
      "8:30-9:30 PM IST is prime time for calls with SF",
    ],
    relatedRoutes: ["ist-to-est", "pst-to-ist", "ist-to-london", "ist-to-cst"],
  },

  "ist-to-gmt": {
    title: "IST to GMT Time Converter",
    shortTitle: "IST → GMT",
    subtitle: "Convert Indian Standard Time to Greenwich Mean Time",
    fromCity: "India",
    toCity: "GMT",
    fromZone: "Asia/Kolkata",
    toZone: "UTC",
    fromGMT: "GMT+5:30",
    toGMT: "GMT+0",
    timeDiff: "5.5 hours behind",
    description: "India Standard Time (IST) is exactly 5 hours and 30 minutes ahead of Greenwich Mean Time (GMT/UTC). This offset never changes as neither IST nor UTC observes daylight saving time.",
    dstNote: "Neither IST nor GMT/UTC observes Daylight Saving Time, so this conversion is consistent year-round.",
    useCases: [
      "Converting to universal time for global events",
      "Scheduling international conferences",
      "Setting up server timestamps",
      "Coordinating across multiple global timezones",
    ],
    bestTimes: "GMT is often used as a reference point. For business hours (9 AM - 5 PM GMT), that's 2:30 PM - 10:30 PM IST.",
    tips: [
      "GMT and UTC are effectively the same for most purposes",
      "Many global platforms use UTC for timestamps",
      "When in doubt, convert to GMT first, then to local time",
    ],
    relatedRoutes: ["ist-to-london", "ist-to-est", "gmt-to-ist"],
  },

  "ist-to-cst": {
    title: "IST to CST Time Converter",
    shortTitle: "IST → CST",
    subtitle: "Convert Indian Standard Time to US Central Time",
    fromCity: "India",
    toCity: "Chicago",
    fromZone: "Asia/Kolkata",
    toZone: "America/Chicago",
    fromGMT: "GMT+5:30",
    toGMT: "GMT-6/-5",
    timeDiff: "11.5 hours behind",
    description: "India Standard Time (IST) is 11.5 hours ahead of Central Standard Time (CST). When it's noon in India, it's 12:30 AM in Chicago/Dallas.",
    dstNote: "During Central Daylight Time (CDT), the difference reduces to 10.5 hours.",
    useCases: [
      "Working with Dallas or Chicago offices",
      "Coordinating with Midwest US companies",
      "Managing teams in Texas or Illinois",
    ],
    bestTimes: "The best overlap is 7:30 PM - 10:30 PM IST (8:00 AM - 11:00 AM CST).",
    tips: [
      "CST is 1 hour ahead of PST and 1 hour behind EST",
      "Major cities: Chicago, Dallas, Houston, Austin",
    ],
    relatedRoutes: ["ist-to-est", "ist-to-pst", "cst-to-ist"],
  },

  // UK/London conversions
  "london-to-ist": {
    title: "London to IST Time Converter",
    shortTitle: "London → IST",
    subtitle: "Convert London Time to Indian Standard Time",
    fromCity: "London",
    toCity: "India",
    fromZone: "Europe/London",
    toZone: "Asia/Kolkata",
    fromGMT: "GMT+0/+1",
    toGMT: "GMT+5:30",
    timeDiff: "5.5 hours ahead",
    description: "London is 5.5 hours behind India Standard Time (IST). When it's noon in London, it's 5:30 PM in India. During British Summer Time (BST), the difference is 4.5 hours.",
    dstNote: "UK observes British Summer Time (BST) from late March to late October.",
    useCases: [
      "UK companies with Indian offshore teams",
      "British businesses with India operations",
      "Expats in UK calling family in India",
    ],
    bestTimes: "UK morning (9 AM - 12 PM) aligns with India afternoon (2:30 PM - 5:30 PM) for optimal overlap.",
    tips: [
      "India does not observe DST, so the offset changes when UK clocks change",
      "London afternoon meetings mean late evening for India participants",
    ],
    relatedRoutes: ["ist-to-london", "london-to-est", "london-to-pst"],
  },

  "london-to-est": {
    title: "London to EST Time Converter",
    shortTitle: "London → EST",
    subtitle: "Convert London Time to US Eastern Time",
    fromCity: "London",
    toCity: "New York",
    fromZone: "Europe/London",
    toZone: "America/New_York",
    fromGMT: "GMT+0/+1",
    toGMT: "GMT-5/-4",
    timeDiff: "5 hours behind",
    description: "London is 5 hours ahead of New York (Eastern Time). When it's noon in London, it's 7:00 AM in New York. Both observe DST, so the difference stays relatively consistent.",
    dstNote: "Both UK and US observe DST, but they change on different dates, causing brief periods of 4 or 6 hour differences.",
    useCases: [
      "Transatlantic business calls",
      "UK-US financial market coordination",
      "International media and news coordination",
    ],
    bestTimes: "London afternoon (2 PM - 5 PM) overlaps well with New York morning (9 AM - 12 PM).",
    tips: [
      "The 'DST gap' in spring and fall can catch you off guard",
      "London markets open as New York closes from the previous day",
    ],
    relatedRoutes: ["est-to-london", "london-to-pst", "london-to-ist"],
  },

  "london-to-pst": {
    title: "London to PST Time Converter",
    shortTitle: "London → PST",
    subtitle: "Convert London Time to US Pacific Time",
    fromCity: "London",
    toCity: "Los Angeles",
    fromZone: "Europe/London",
    toZone: "America/Los_Angeles",
    fromGMT: "GMT+0/+1",
    toGMT: "GMT-8/-7",
    timeDiff: "8 hours behind",
    description: "London is 8 hours ahead of Los Angeles (Pacific Time). When it's noon in London, it's 4:00 AM in California. This makes real-time collaboration challenging.",
    dstNote: "Both observe DST but on different schedules, causing brief periods of 7 or 9 hour differences.",
    useCases: [
      "UK companies with Silicon Valley partnerships",
      "European VCs working with US West Coast startups",
      "Entertainment industry coordination (Hollywood-London)",
    ],
    bestTimes: "Late London afternoon (4 PM - 6 PM) catches early California morning (8 AM - 10 AM).",
    tips: [
      "Morning London meetings mean middle-of-night for California",
      "Consider async video updates for this timezone pair",
    ],
    relatedRoutes: ["pst-to-london", "london-to-est", "london-to-ist"],
  },

  // US timezone conversions
  "est-to-pst": {
    title: "EST to PST Time Converter",
    shortTitle: "EST → PST",
    subtitle: "Convert Eastern Time to Pacific Time",
    fromCity: "New York",
    toCity: "Los Angeles",
    fromZone: "America/New_York",
    toZone: "America/Los_Angeles",
    fromGMT: "GMT-5/-4",
    toGMT: "GMT-8/-7",
    timeDiff: "3 hours behind",
    description: "Eastern Time is 3 hours ahead of Pacific Time. When it's noon in New York, it's 9:00 AM in Los Angeles. This difference is consistent year-round as both zones observe DST simultaneously.",
    dstNote: "Both EST and PST observe Daylight Saving Time on the same dates, maintaining the 3-hour difference.",
    useCases: [
      "Coast-to-coast US business coordination",
      "Nationwide conference calls",
      "TV broadcast scheduling",
      "Sports event timing",
    ],
    bestTimes: "The overlap is excellent: 9 AM - 5 PM EST (6 AM - 2 PM PST) or 12 PM - 8 PM EST (9 AM - 5 PM PST).",
    tips: [
      "Always specify the timezone when scheduling US-wide meetings",
      "East Coast meetings at 9 AM mean 6 AM for West Coast - not ideal",
      "Midday EST works best for both coasts",
    ],
    relatedRoutes: ["pst-to-est", "est-to-cst", "est-to-ist"],
  },

  "pst-to-est": {
    title: "PST to EST Time Converter",
    shortTitle: "PST → EST",
    subtitle: "Convert Pacific Time to Eastern Time",
    fromCity: "Los Angeles",
    toCity: "New York",
    fromZone: "America/Los_Angeles",
    toZone: "America/New_York",
    fromGMT: "GMT-8/-7",
    toGMT: "GMT-5/-4",
    timeDiff: "3 hours ahead",
    description: "Pacific Time is 3 hours behind Eastern Time. When it's noon in Los Angeles, it's 3:00 PM in New York.",
    dstNote: "The 3-hour difference is consistent year-round.",
    useCases: [
      "West Coast companies with East Coast clients",
      "Tech companies with Wall Street partnerships",
      "US-wide product launches",
    ],
    bestTimes: "9 AM PST (12 PM EST) to 2 PM PST (5 PM EST) provides full overlap during business hours.",
    tips: [
      "Start of business in California is lunch time in New York",
      "End of day in New York is mid-afternoon in California",
    ],
    relatedRoutes: ["est-to-pst", "pst-to-ist", "pst-to-london"],
  },

  "est-to-cst": {
    title: "EST to CST Time Converter",
    shortTitle: "EST → CST",
    subtitle: "Convert Eastern Time to Central Time",
    fromCity: "New York",
    toCity: "Chicago",
    fromZone: "America/New_York",
    toZone: "America/Chicago",
    fromGMT: "GMT-5/-4",
    toGMT: "GMT-6/-5",
    timeDiff: "1 hour behind",
    description: "Eastern Time is 1 hour ahead of Central Time. When it's noon in New York, it's 11:00 AM in Chicago.",
    dstNote: "Both zones observe DST on the same schedule, maintaining the 1-hour difference.",
    useCases: [
      "NYC-Chicago business coordination",
      "Financial services with Midwest offices",
      "National retail operations",
    ],
    bestTimes: "Near-perfect overlap during business hours with just 1 hour difference.",
    relatedRoutes: ["cst-to-est", "est-to-pst", "cst-to-pst"],
  },

  // Reverse conversions (for SEO completeness)
  "gmt-to-ist": {
    title: "GMT to IST Time Converter",
    shortTitle: "GMT → IST",
    subtitle: "Convert Greenwich Mean Time to Indian Standard Time",
    fromCity: "GMT",
    toCity: "India",
    fromZone: "UTC",
    toZone: "Asia/Kolkata",
    fromGMT: "GMT+0",
    toGMT: "GMT+5:30",
    timeDiff: "5.5 hours ahead",
    description: "GMT/UTC is 5.5 hours behind India Standard Time. When it's noon GMT, it's 5:30 PM in India.",
    useCases: [
      "Converting UTC timestamps to IST",
      "International event scheduling",
      "Server time to local time conversion",
    ],
    bestTimes: "GMT business hours (9 AM - 5 PM) correspond to IST 2:30 PM - 10:30 PM.",
    relatedRoutes: ["ist-to-gmt", "ist-to-london", "gmt-to-est"],
  },

  "est-to-ist": {
    title: "EST to IST Time Converter",
    shortTitle: "EST → IST",
    subtitle: "Convert US Eastern Time to Indian Standard Time",
    fromCity: "New York",
    toCity: "India",
    fromZone: "America/New_York",
    toZone: "Asia/Kolkata",
    fromGMT: "GMT-5/-4",
    toGMT: "GMT+5:30",
    timeDiff: "10.5 hours ahead",
    description: "Eastern Time is 10.5 hours behind India Standard Time. When it's noon in New York, it's 10:30 PM in India.",
    useCases: [
      "US East Coast with India offshore teams",
      "American companies with India operations",
      "US-India business development",
    ],
    bestTimes: "US morning (8-10 AM EST) aligns with India evening (6:30-8:30 PM IST).",
    relatedRoutes: ["ist-to-est", "est-to-pst", "est-to-london"],
  },

  "pst-to-ist": {
    title: "PST to IST Time Converter",
    shortTitle: "PST → IST",
    subtitle: "Convert US Pacific Time to Indian Standard Time",
    fromCity: "San Francisco",
    toCity: "India",
    fromZone: "America/Los_Angeles",
    toZone: "Asia/Kolkata",
    fromGMT: "GMT-8/-7",
    toGMT: "GMT+5:30",
    timeDiff: "13.5 hours ahead",
    description: "Pacific Time is 13.5 hours behind India Standard Time. When it's noon in San Francisco, it's 1:30 AM the next day in India.",
    useCases: [
      "Silicon Valley with India engineering teams",
      "Bay Area startups with Bangalore offices",
      "West Coast VCs with India portfolio companies",
    ],
    bestTimes: "PST early morning (7-9 AM) catches IST evening (8:30-10:30 PM). This is the standard for US-India standups.",
    tips: [
      "The infamous '8:30 AM PST standup' is 10 PM IST",
      "Bangalore is often called 'the city that never sleeps' due to US timezone sync",
    ],
    relatedRoutes: ["ist-to-pst", "pst-to-est", "pst-to-london"],
  },

  "cst-to-ist": {
    title: "CST to IST Time Converter",
    shortTitle: "CST → IST",
    subtitle: "Convert US Central Time to Indian Standard Time",
    fromCity: "Chicago",
    toCity: "India",
    fromZone: "America/Chicago",
    toZone: "Asia/Kolkata",
    fromGMT: "GMT-6/-5",
    toGMT: "GMT+5:30",
    timeDiff: "11.5 hours ahead",
    description: "Central Time is 11.5 hours behind India Standard Time. When it's noon in Chicago, it's 11:30 PM in India.",
    useCases: [
      "Dallas/Houston tech companies with India teams",
      "Midwest businesses with India operations",
    ],
    bestTimes: "CST morning (8-10 AM) aligns with IST evening (7:30-9:30 PM).",
    relatedRoutes: ["ist-to-cst", "cst-to-est", "cst-to-pst"],
  },

  // More UK reverse conversions
  "est-to-london": {
    title: "EST to London Time Converter",
    shortTitle: "EST → London",
    subtitle: "Convert US Eastern Time to London Time",
    fromCity: "New York",
    toCity: "London",
    fromZone: "America/New_York",
    toZone: "Europe/London",
    fromGMT: "GMT-5/-4",
    toGMT: "GMT+0/+1",
    timeDiff: "5 hours ahead",
    description: "Eastern Time is 5 hours behind London. When it's noon in New York, it's 5:00 PM in London.",
    useCases: [
      "Wall Street with London financial markets",
      "US media with UK correspondents",
      "Transatlantic business partnerships",
    ],
    bestTimes: "EST morning (9 AM - 12 PM) overlaps with London afternoon (2 PM - 5 PM).",
    relatedRoutes: ["london-to-est", "est-to-pst", "est-to-ist"],
  },

  "pst-to-london": {
    title: "PST to London Time Converter",
    shortTitle: "PST → London",
    subtitle: "Convert US Pacific Time to London Time",
    fromCity: "Los Angeles",
    toCity: "London",
    fromZone: "America/Los_Angeles",
    toZone: "Europe/London",
    fromGMT: "GMT-8/-7",
    toGMT: "GMT+0/+1",
    timeDiff: "8 hours ahead",
    description: "Pacific Time is 8 hours behind London. When it's noon in Los Angeles, it's 8:00 PM in London.",
    useCases: [
      "Hollywood with UK film industry",
      "West Coast tech with London offices",
      "California businesses with UK partners",
    ],
    bestTimes: "PST early morning (8-10 AM) catches London late afternoon (4-6 PM).",
    relatedRoutes: ["london-to-pst", "pst-to-est", "pst-to-ist"],
  },

  // Additional high-volume searches
  "gmt-to-est": {
    title: "GMT to EST Time Converter",
    shortTitle: "GMT → EST",
    subtitle: "Convert Greenwich Mean Time to US Eastern Time",
    fromCity: "GMT",
    toCity: "New York",
    fromZone: "UTC",
    toZone: "America/New_York",
    fromGMT: "GMT+0",
    toGMT: "GMT-5/-4",
    timeDiff: "5 hours behind",
    description: "GMT/UTC is 5 hours ahead of Eastern Standard Time. When it's noon GMT, it's 7:00 AM in New York.",
    useCases: [
      "Converting international event times to EST",
      "Server timestamps to local time",
      "Global coordination with US East Coast",
    ],
    bestTimes: "GMT afternoon aligns with EST morning business hours.",
    relatedRoutes: ["est-to-gmt", "gmt-to-ist", "gmt-to-pst"],
  },

  "cst-to-pst": {
    title: "CST to PST Time Converter",
    shortTitle: "CST → PST",
    subtitle: "Convert Central Time to Pacific Time",
    fromCity: "Chicago",
    toCity: "Los Angeles",
    fromZone: "America/Chicago",
    toZone: "America/Los_Angeles",
    fromGMT: "GMT-6/-5",
    toGMT: "GMT-8/-7",
    timeDiff: "2 hours behind",
    description: "Central Time is 2 hours ahead of Pacific Time. When it's noon in Chicago, it's 10:00 AM in Los Angeles.",
    useCases: [
      "Midwest to West Coast business coordination",
      "Dallas-LA business calls",
      "National retail operations",
    ],
    bestTimes: "Excellent overlap with just 2 hours difference.",
    relatedRoutes: ["pst-to-cst", "cst-to-est", "cst-to-ist"],
  },
};

// SEO data generator for converter pages
export function getConverterSEO(route) {
  const data = CONVERTER_ROUTES[route];
  if (!data) return null;

  return {
    title: `${data.title} | Free Time Zone Calculator - GeoSyncX`,
    description: `${data.description.slice(0, 155)}...`,
    keywords: `${data.fromCity} to ${data.toCity} time, ${route.replace(/-/g, " ")}, timezone converter, time difference calculator, ${data.fromZone} to ${data.toZone}`,
    author: "GeoSyncX Team",
    url: `https://www.geosyncx.com/time/${route}`,
    type: "website",
    image: "https://www.geosyncx.com/android-chrome-512x512.png",
  };
}

// Get all route keys for sitemap generation
export function getAllConverterRoutes() {
  return Object.keys(CONVERTER_ROUTES);
}
